import 'package:flutter/material.dart';

@immutable
class StringConstant {
  static const appTitle = 'Tarladan';
  static const customer = 'Müşteri';
  static const seller = 'Satıcı';
  static const signUp = 'Kaydol';
  static const nameSurname = 'Ad Soyad';
  static const mail = 'E-posta';
  static const password = 'Şifre';
  static const noSignAccountText = 'Hesabınız var mı? Giriş yapın';
  static const loginFailed = 'Kayıt başarısız';
  static const signIn = 'Giriş Yap';
  static const noLoginAccountText = 'Hesabınız yok mu? Kaydolun';
  static const signInFailed = 'Giriş başarısız oldu!';
  static const products = 'Ürünler';
  static const orders = 'Siparişler';
  static const addProduct = 'Ürün Ekle';
  static const nameProduct = 'Ürün Adı';
  static const price = 'Fiyat(TL)';
  static const description = 'Açıklama';
  static const amount = 'Miktar(KG)';
  static const deliveryTime = 'Teslimat Süresi(gün)';
  static const noDateDeliveryTime = 'Teslimat Süresi';
  static const deliveryArea = 'Teslimat Bölgesi';
  static const noProductYet = 'Henüz ürün yok.';
  static const noNameSeller = 'İsimsiz Satıcı';
  static const unknownSeller = 'Bilinmeyen Satıcı';
  static const noSellerInfo = 'Satıcı Bilgisi Alınamadı';
  static const error = 'Hata';
  static const noProductInfo = 'Ürün bilgisi bulunamadı';
  static const comments = 'Yorumlar';
  static const noCommentsYet = 'Henüz yorum yok';
  static const buy = 'Satın Al';
  static const sellerNameError = 'Satıcı adı alınırken hata oluştu';
  static const anErrorOccurred = 'Bir hata oluştu';
  static const noOrdersYet = 'Henüz siparişiniz bulunmamaktadır';
  static const status = 'Durum';
  static const loading = 'Yükleniyor...';
  static const myOrders = 'Siparişlerim';
  static const pending = 'beklemede';
  static const completed = 'tamamlandı';
  static const unknown = 'bilinmiyor';
  static const editProfile = 'Profili Düzenle';
  static const profile = 'Profil';
  static const role = 'Rol';
  static const cancel = 'İptal';
  static const exit = 'Çıkış Yap';
  static const areYouSureToExit =
      'Hesaptan çıkış yapmak istediğinize emin misiniz?';
  static const changePassword = 'Şifre Değiştir';
  static const save = 'Kaydet';
  static const currentPassword = 'Mevcut Şifre';
  static const newPassword = 'Yeni Şifre';
  static const confirmNewPassword = 'Yeni Şifre (Tekrar)';
  static const pleaseEnterName = 'Lütfen adınızı girin';
  static const pleaseEnterCurrentPassword = 'Lütfen mevcut şifrenizi girin';
  static const pleaseEnterNewPassword = 'Lütfen yeni şifrenizi girin';
  static const passwordMustBeAtLeast6Characters =
      'Şifre en az 6 karakter olmalıdır';
  static const passwordsDoNotMatch = 'Şifreler eşleşmiyor';
  static const edit = 'Düzenle';
  static const profileUpdatedSuccessfully = 'Profil başarıyla güncellendi';
  static const phoneNumber = 'Telefon Numarası';
  static const phone = 'Telefon';
  static const productDeleteError = 'Ürün silinirken bir hata oluştu';
  static const deleteProduct = 'Ürünü Sil';
  static const delete = 'Sil';
  static const deleteOrder = 'Siparişi Sil';
  static const areYouSureDeleteThisOrder =
      'Bu siparişi silmek istediğinize emin misiniz?';
  static const orderDetail = 'Sipariş Detayı';
  static const send = 'Gönder';
  static const orderID = 'Sipariş ID';
  static const product = 'Ürün';
  static const amountOrder = 'Miktar';
  static const totalPrice = 'Toplam Fiyat';
  static const orderDate = 'Sipariş Tarihi';
  static const deliveryInfo = 'Teslimat Bilgileri';
  static const region = 'Bölge';
  static const estimatedDeliveryTime = 'Tahmini Teslimat Süresi';
  static const evaluateProduct = 'Ürünü Değerlendirin';
  static const writeYourComment = 'Yorumunuzu buraya yazın...';
  static const pleaseSelectAStar = 'Lütfen bir yıldız değeri seçin';
  static const productNotFound = 'Ürün bulunamadı';
  static const evaluationSuccesfullySaved =
      'Değerlendirme başarıyla kaydedildi';
  static const orderStatusUpdated = 'Sipariş durumu güncellendi';
  static const customerID = 'Müsteri ID:';
  static const noNameCustomer = 'İsimsiz Müşteri';
  static const unknownCustomer = 'Bilinmeyen Müşteri';
  static const noCustomerInfo = 'Müşteri Bilgisi Alınamadı';
  static const customerNameError = 'Müşteri adı alınırken hata oluştu';
  static const ratingError = "Ortalama puan hesaplanırken bir hata oluştu";
  static const reviewDeleted = 'Yorum başarıyla silindi';
  static const errorDeletingReview = 'Yorum silinirken bir hata oluştu';
  static const userNotLoggedIn = 'Kullanıcı oturum açmamış';
  static const noCommentsFound = 'Yorum bulunamadı';
  static const notAuthorizedDeleteThisComment = 'Bu yorumu silme yetkiniz yok';
  static const deleteReviewTitle = 'Yorumu Sil';
  static const deleteReviewConfirmation =
      'Bu yorumu silmek istediğinizden emin misiniz?';
  static const saveChanges = "Değişiklikleri Kaydet";
}
